<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\5\14 0014
 * Time: 21:14
 */

namespace app\admin\controller;


use app\admin\logic\LAd;
use app\admin\model\AdModel;
use app\model\AdTypeModel;
use think\Db;
use Think\Exception;

class Ad extends Base
{
    private $adModel;
    private $adTypeModel;
    private $status = [
        '0' => '未审核',
        '1' => '审核通过',
        '-1' => '审核驳回'
    ];
    private $types;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->adModel = new AdModel();
        $this->adTypeModel = new AdTypeModel();
        $this->types = Db::name('adType')->column('id,name');
    }
    public function index() {
        $val = input('key');
        $where = [];
        if(isset($val) && !empty($val)) {
            $where['title'] = ['like' , '%'.$val.'%'];
        }
        $Nowpage = input('get.page') ? input('get.page'):1;
        $limits = 10;// 获取总条数
        $count = Db::name('ad')->where($where)->count();//计算总页面
        $allpage = intval(ceil($count / $limits));
        if(input('get.page')){
            $lists = Db::name('ad')->where($where)->page($Nowpage, $limits)->order('field(status,0,1,2)')->select();
            $adTypes = Db::name('adType')->column('id,name');
            $members = Db::name('agency')->column('id,nick_name');
            foreach ($lists as &$val) {
                $val['type_name'] = $adTypes[$val['type']];
                $val['member_name'] = $members[$val['mid']];
                $val['state'] = $this->status[$val['status']];
            }
            return json($lists);
        }
        $this->assign('Nowpage', $Nowpage); //当前页
        $this->assign('allpage', $allpage); //总页数
        $this->assign('val',$val);
        return $this->fetch();
    }
    /**
     * 审核
     */
    public function check() {
        if($this->request->isAjax()){
            $id = input('id');
            $state = input('state');
            if($state == 1){
                $res = LAd::adCheck($id);
                if($res['code'] == 1) {
                    //审核成功
                    $where = array(
                        'ad' => $id
                    );
                    $update = array(
                        'status' => 1
                    );
                    Db::name('ad_member')->where($where)->update($update);
                    $res['url'] = url('index');
                    return json($res);
                }else {
                    return json($res);
                }
            }else {
                $where = array(
                    'id' => $id
                );
                $update = array(
                    'status' => -1
                );
                try {
                    $this->adModel->where($where)->update($update);
                    return json(['code' => 1,'msg' => '操作成功!','url' => url('index') ]);
                }catch (Exception $e) {
                    return json(['code' => -99,'msg' => $e->getMessage()]);
                }
            }
        }
        $id = input('id');
        $info = $this->adModel->where('id',$id)->find();
        $where = array(
            'id' => $info['type']
        );
        $info['type_name'] = $this->adTypeModel->where($where)->value('name');
        $this->assign('info',$info);
        return $this->fetch();
    }
    //查看某个代理的广告
    public function look() {
        $member = input('member');
        $where = [
            'mid' => $member
        ];
        $val = input('key');
        if(isset($val) && !empty($val)) {
            $where['title'] = ['like' , '%'.$val.'%'];
        }
        $Nowpage = input('get.page') ? input('get.page'):1;
        $limits = 10;// 获取总条数
        $count = Db::name('ad')->where($where)->count();//计算总页面
        $allpage = intval(ceil($count / $limits));
        if(input('get.page')){
            $lists = Db::name('ad')->where($where)->page($Nowpage, $limits)->order('field(status,0,1,2)')->select();
            $adTypes = Db::name('adType')->column('id,name');
            $members = Db::name('agency')->column('id,nick_name');
            foreach ($lists as &$val) {
                $val['type_name'] = $adTypes[$val['type']];
                $val['member_name'] = $members[$val['mid']];
                $val['state'] = $this->status[$val['status']];
            }
            return json($lists);
        }
        $this->assign('Nowpage', $Nowpage); //当前页
        $this->assign('allpage', $allpage); //总页数
        $this->assign('val',$val);
        $this->assign('member',$member);
        return $this->fetch();
    }

    /**
     * 编辑
     */
    public function edit(){
        if($this->request->isPost()) {
            $params = input('post.');
            $where = [
                'id' => $params['id']
            ];
            try {
                Db::name('ad')->where($where)->update($params);
                return json(['code' => '1','msg' => '更新成功!','url' => url('index')]);
            }catch (Exception $e) {
                return json(['code' => '-99', 'msg' => $e->getMessage()]);
            }
        }
        $id = input('id');
        $where = [
            'id' => $id
        ];
        $data = Db::name('ad')->where($where)->find();
        $this->assign('data',$data);
        $this->assign('types',$this->types);
        return $this->fetch();
    }

    /**
     * 删除
     */
    public function del() {
        if(request()->isAjax()){
            $where = [
                'id' => input('id')
            ];
            //删除
            try {
                Db::name('ad')->where($where)->delete();
                return json(['code' => '1','msg' => '删除成功!','url' => url('index')]);
            }catch (Exception $e) {
                return json(['code' => -99,'msg' => $e->getMessage()]);
            }
        }
    }
}